### ISSUE TITLE
NUCLEO_F429ZI + Atmel AT233 + mbed 6LoWPAN gateway : device connector failure.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-client#10]
Steps to reproduce:
$> mbed import https://github.com/ARMmbed/oob-mbed-os-example-client
$>  ... update mbed OS to rc2 ...
-- login to device connector, download security credentials and change it in security.h
-- check mbed_app.json for appropriate network interface and radio type and features_add (nanostack)
$> mbed compile -t ARM -m NUCLEO_F429ZI
-- Update firmware on border router with 6LoWPANStatic.bin, restart and wait for it to acquire IP address
-- copy *.bin to target and wait for it to reset.

Output:
1. Router connects to IP - OK.
2. Target connects to IPv6 network with valid address - OK.
3. Target starts simulating button presses with a counter - OK.
4. Device connector does not "see" the device - FAIL.

Screenshot below. COM14 = Router, COM12 = Target (Nucleo_F429ZI + AT233 with chip antenna)
![nucleo_f429zi_at233_armcc_connector_failure](https://cloud.githubusercontent.com/assets/17567812/19346886/a5f541c6-913d-11e6-87ad-fe0b2891fb4f.jpg)

**Comment by ashok-rao** [comment]
Issue also seen with GCC. However, in the case of GCC, the application fails on the target itself. Screenshot below. The mbed_app.json file is the same as seen in the screenshot in previous comment.

![nucleo_f429zi_at233_gcc_app_fail](https://cloud.githubusercontent.com/assets/17567812/19347023/a2a5466e-913e-11e6-85f9-463f379c7d2a.jpg)

**Comment by ashok-rao** [comment]
[EDIT] : Using 6LoWPANDynamic.bin on the border router and using an IPv6 tunnel solves the issue with ARMCC. Testing now with GCC and IAR.

Will close the issue if all is well.

**Comment by SeppoTakalo** [comment]
This is related: https://github.com/ARMmbed/oob-mbed-os-example-mesh-minimal/issues/3

So most probably a same issue.

**Comment by MarceloSalazar** [comment]
Issue fixed. Please re-test in RC3.

**Comment by ashok-rao** [comment]
Fixed in RC3. Closing. Thank you.
