### ISSUE TITLE
Example does not work with Nucleo-F401RE

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/oob-mbed-os-example-client#15]
Setup:

mbed-os ver: mbed-os-5.2.0-rc3
Platform: NUCLEO_F401RE
Radio shield: ATMEL with chip antenna
Toolchains: GCC_ARM and ARM

I am receiving error code -3012

**Comment by SeppoTakalo** [comment]
Tested with GCC_ARM.
The board won't even start. No output on serial port.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1118

**Comment by c1728p9** [comment]
Hi @hasnainvirk, I'm able to reproduce this problem. It is caused from the LEDs added [here](https://github.com/ARMmbed/mbed-os-example-client/pull/79/files#diff-118fcbaaba162ba17933c7893247df3aR61). The values LED1, LED2, LED3 each map to PA_5 as seen in [pinmap.h](https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F401RE/PinNames.h#L157). This pin is SPI clock so without it there is no communication with the atmel chip. Removing all 3 leds from the example fixes this platform.

**Comment by SeppoTakalo** [comment]
Ah. Thanks @c1728p9 for finding the root cause.

**Comment by jankii01** [comment]
So, what's the solution proposal then for this? We can't tweak the freakin' app for every single board. The pinmap needs to be per board and well, if there are pin conflicts then the pinmap needs to prioritize vital pins over LED pins and connect the LED pins to "NC" or other dummy location that doesn't hurt bootup etc.

**Comment by kjbracey-arm** [comment]
Someone needs to configure the system as a whole - I don't see how this can be totally automatic. And the configuration will depend what they're trying to do with the system, in the event of this sort of clash. They would need to know that they were using a radio module, and that they prioritised it over LEDs.

The base target pinmaps are "optimistic" in that they tell you all the wiring, they don't tell you what things can be used together.

The continuing problem is the fact that people are (sensibly) trying to make applications portable, but they are the place where "system+application-specific" configuration needs to be done. mbed has no separate "system control" place to bind stuff together, separate from the sole "application".

So you do in general need to tweak every moderately-complex app for every single board + riser combo. mbed's portability abstraction only really goes as far as "blinky" and "ping test using on-board network interface".

In Nanomesh we dealt with this (somewhat) by separating the board initialisation from the tasklets. main.c was always solely system-specific initialisation - that then linked with application-portable board init code and board-portable application tasklets. 

In mbed, the system concept is very much "monolithic". The application contains the system configuration. And there's no separate place to pick up common tasklets.

**Comment by jankii01** [comment]
So, it's a matter of documenting 
1) which are the references we ensure will work straight out of box
2) documenting WHAT needs to be changed and HOW in the "usual cases"
Some of the boards will always fail and the develop in question just needs to be clever enough to know how to sort it out...

**Comment by c1728p9** [comment]
Many boards adhere to the Arduino pin naming convention allowing them to be used without modifications. Boards that don't typically cause an error at compile time since the necessary pins are missing. The change [here](https://github.com/ARMmbed/mbed-os-example-client/pull/79/files#diff-118fcbaaba162ba17933c7893247df3aR61) added pins which are not part of a standard layout and thus board specific. If LED1,2,3 are removed then the code would be a lot more portable.

**Comment by MarceloSalazar** [comment]
@SeppoTakalo can you fix this following these findings https://github.com/ARMmbed/oob-mbed-os-example-client/issues/15#issuecomment-254681325

**Comment by hasnainvirk** [comment]
@MarceloSalazar This platform will not be able to run this example. Current RAM requirement of client_example+mbedtls+mbed-os is 140K. I had tried yesterday, and I kept getting alloc errors from mbedtls. Which implies that we were running out of RAM consistently.

**Comment by hasnainvirk** [comment]
If we happen to resolve the pin clashes for this platform, running mbed-os-example-client is not trivial with the likes of this platform.  Quite a lot of optimization steps would be needed. Some of them are not recommended for production quality builds.
Recently we had pulled off such an optimization exercise with a platform which has pretty restrictive resources. I will summarize the steps we undertook:

* We did not use mbed-client
* We did not use coap-service
* We did not use any abstraction provided by mbed-os. 
* We set the OS_TASKCNT to 4 which means only 4 threads allowed.
* Stack sizes for each thread were manually defined.
* Application used custom logic to pull off DTLS handshake (with beta connector). This was way lighter than a combination of Client+CoAP service. And ofcourse it is not production quality as it is very much simplified.
* We merged the heap that Nanostack and mbed-os would use. So that we could squeeze every single droplet of RAM left.
* We reduced the usage of MBEDTLS cipher suites to only 1 which was necessary for the operation.
* We swapped AES tables from RAM to ROM.
* MBEDTLS_ECP_MAX_BITS was set to 256
* MBEDTLS_MPI_MAX_SIZE was set to 32
* MBEDTLS_ECP_WINDOW_SIZE was set to 4
* MBEDTLS_ECP_FIXED_POINT_OPTIM was set to 0. The above mentioned steps reduce peak memory usage as a trade off with speed.
* MBEDTLS_SSL_MAX_CONTENT_LEN was set to 1K
In the application logic, we set MBEDTLS_SSL_VERIFY_NONE which is absolutely a security risk for production quality builds. It implies that the application will not verify the certificate sent by the Connector.
* Application logic used nanostack's eventloop directly because we wanted to save RAM by not using mbed-os abstraction layers.  mbed-os abstractions put extra overhead in terms of static data. Every object creation would result in calling of the respective constructor which adds up to the static data counter. Hence increasing RAM consumption.

There still be some optimizations which I might be missing here. That's why I am inclined to think that fitting to platforms like Nucleo-F401RE is not a trivial task.

**Comment by MarceloSalazar** [comment]
Thanks for the detailed analysis! This is very useful.
We need to learn from this and find a solution for the following release, but agreed not for 5.2.

**Comment by SeppoTakalo** [comment]
Do we need to keep these open?
How many "example does not work with <unsupported board>" we need.

F401RE does not have entropy ,has pin clashes and not enough RAM. This issue will never be fixed.

**Comment by hasnainvirk** [comment]
I agree with @SeppoTakalo. Closing the issue.

**Comment by jankii01** [comment]
Yep, close it out. That board should be dropped from the mbedOS supported boards list then.

**Comment by kjbracey-arm** [comment]
Which list? Not every board is powerful enough to run every application.

The readme here seems to have a pretty good summary of what capabilities are required, and lists some example boards meeting those requirements.
