### ISSUE TITLE
Custom TLS Configuration is not compliant to IETF standards

### ISSUE THREAD

**Issue by sbutcher-arm** [ARMmbed/oob-mbed-os-example-client#22]
The constant `MBEDTLS_SSL_MAX_CONTENT_LEN` has been set in [mbedtls_mbed_client_config.h ](https://github.com/ARMmbed/oob-mbed-os-example-client/blob/mbed-client-rc/mbedtls_mbed_client_config.h) to a maximum record length of 2kb, which could potentially cause interoperability problems and will mean we are no longer compliant with IETF standards.

Functionally this will work if we can be confident both ends will never send a record greater than 2kb, but as sample code it will be copied and pasted and is a bad example to copy.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1129

**Comment by jankii01** [comment]
@yogpan01 already commented in the emails that we are 100% sure we don't exceed that block size in Cloud Connect / mbedConnect. The comment above says it's that way to save RAM. We've also added a note about that to the known issues & limitations document for the Cloud Client (pull REQ) 

https://github.com/ARMmbed/mbed-cloud-client/pull/54

Would something similar be enough also here?

**Comment by jankii01** [comment]
Or add something like this as well? 

diff --git i/mbedtls_mbed_client_config.h w/mbedtls_mbed_client_config.h
index 9874a94..4acae27 100644
--- i/mbedtls_mbed_client_config.h
+++ w/mbedtls_mbed_client_config.h
@@ -1,6 +1,15 @@
-/*
+/**
  *  Minimal configuration for using mbedtls as part of mbed-client
  *
+ *  NOTE! This is a optimized, minimal configuration for mbed Client.
+ *  We know it works with mbed Client but if you want to add more 
+ *  services/communications to the application yourself - please ensure 
+ *  you update this configuration accordingly. The default configuration
+ *  can be found from mbedTLS Github:
+ *
+ *  https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/config.h
+ *
+ *

**Comment by jankii01** [comment]
https://github.com/ARMmbed/mbed-os-example-client/pull/98

**Comment by jankii01** [comment]
It's now merged in.
