### ISSUE TITLE
[Documentation]: No URI field in device connector.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-client#7]
Current documentation says:
"Enter https://api.connector.mbed.com/endpoints/DEVICE_NAME/3200/0/5501 in the URI field and click TEST API. Replace DEVICE_NAME with your actual endpoint name."

But there is no URI field in device connector. Users need to click the "GET" request, select their endpoint and resource from the drop down and then click on "TEST API". Please amend documentation accordingly.

**Comment by SeppoTakalo** [comment]
@ashok-rao Thank you for your report. Valid point, I will amend the documentation.

**Comment by sg-** [comment]
@yogpan01 can you update the docs?

**Comment by yogpan01** [comment]
@sg-  I guess @SeppoTakalo will update this. Let me know if you need help in merging the fix or you can directly amend the documentation file

**Comment by MarceloSalazar** [comment]
@SeppoTakalo would you be able to update this asap?

**Comment by hasnainvirk** [comment]
Documentation updated in https://github.com/ARMmbed/oob-mbed-os-example-client/pull/14

**Comment by ashok-rao** [comment]
Issue resolved. Closing. Thank you.
