### ISSUE TITLE
(documentation) use mbed CLI command

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-client#9]
These are the instructions that explain how to get started with this example:
https://github.com/ARMmbed/oob-mbed-os-example-client#building-the-example

It suggests to clone the repository and run 'mbed update'. However, I believe we should update this example and align with the recommended way of working with tools. For example:

1. Import the example
'mbed import mbed-os-example-blinky'  (for this oob example, it would be 'oob-mbed-os-example-blinky')

2. Update to the stable release, for example:
'mbed update mbed-os-5.2.0'

Thoughts?

**Comment by SeppoTakalo** [comment]
Where is this "recommended way of working" documented?

**Comment by MarceloSalazar** [comment]
The documentation from docs.mbed.com states mbed CLI as the offline development tool:
https://docs.mbed.com/docs/mbed-os-handbook/en/5.1/

We should align the docs on the "official" examples on how to get started so developers do not get confused and have a decent user experience.

cc @iriark01  @BlackstoneEngineering

**Comment by sg-** [comment]
We shouldnt update dependencies by default. If git clone is used then someone should ```mbed deploy``` to locally the program as it was published. From there you can ```cd``` and ```mbed update``` dependencies if needed.

**Comment by iriark01** [comment]
You need @peknis01 for Client, not me

**Comment by MarceloSalazar** [comment]
Proposed changes: https://github.com/ARMmbed/oob-mbed-os-example-client/pull/12

@peknis01

**Comment by yogpan01** [comment]
@MarceloSalazar  Merged now #12 . Can be closed

**Comment by MarceloSalazar** [comment]
thanks
